on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout main
      uses: actions/checkout@main

    - name: Build container image
      run: docker build -t ghcr.io/starburst997/mail-forward:latest .

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log in docker
      run: echo ${{ secrets.PAT }} | docker login ghcr.io -u starburst997 --password-stdin

    - name: Push image to DigitalOcean Container Registry
      run: docker push ghcr.io/starburst997/mail-forward:latest

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 notessimo

    - name: Start deployment
      run: kubectl rollout restart deployment/mail-forward --namespace=mail-forward

    - name: Verify deployment
      run: kubectl rollout status deployment/mail-forward --namespace=mail-forward
